#pragma once

#include <cassert>
#include <expected>
#include <iterator>
#include <ranges>
#include <span>
#include <string>
#include <string_view>
#include <vector>

#include "option.h"

namespace kota::option {

/// Per-parse configuration: controls parsing behavior and option filtering.
/// Separate from OptTable so the same table can be parsed with different strategies.
struct ParseOptions {
    /// Support grouped short options, e.g. -abc represents -a -b -c.
    bool grouped_short_options = false;

    /// Whether "--" stops option parsing and treats all subsequent
    /// arguments as positional. E.g. `-- -a -b` gives two positional inputs.
    bool dash_dash_parsing = false;

    /// When dash_dash_parsing is on, pack everything after "--" into a single
    /// ParsedArg whose spelling is "--" and values contain the rest of argv.
    bool dash_dash_packing = false;

    /// Search from index 0 instead of first_searchable_index, so that Input
    /// and Unknown entries also participate in the prefix/name scan.
    bool input_random_index = false;

    /// The option infos are sorted by name (e.g. generated by TableGen),
    /// so use binary search instead of linear scan.
    bool tablegen_mode = false;

    /// Unknown options greedily consume subsequent values until a known
    /// option or "--" is encountered.
    bool greedy_unknown = false;

    /// Bitmask: only match options whose visibility intersects this value.
    std::uint32_t visibility = ~0U;

    /// If non-zero, only match options that carry at least one of these flags.
    std::uint32_t include_flags = 0;

    /// Exclude options that carry any of these flags.
    std::uint32_t exclude_flags = 0;

    bool excludes(const OptionRef& opt) const;
};

using ArgAccessFn = std::string_view (*)(const void* data, std::uint32_t index);

/// Immutable option definition table. Built once from a span of Option entries;
/// the constructor scans for input/unknown IDs, computes prefix data, and
/// determines the first searchable index. All fields are public and read-only
/// after construction.
struct OptTable {
    std::span<const Option> option_infos;
    std::vector<std::string_view> prefixes_union;
    std::vector<char> prefix_chars;
    std::uint32_t input_option_id = 0;
    std::uint32_t unknown_option_id = 0;
    std::uint32_t first_searchable_index = 0;
    bool ignore_case = false;

    OptTable(std::span<const Option> option_infos,
             bool ignore_case = false,
             std::vector<std::string_view> prefixes_union = {});

    std::optional<OptionRef> option(std::uint32_t opt_id) const;

    std::optional<OptionRef> find_option(std::string_view argument,
                                         std::uint32_t visibility = ~0U) const;
};

int parse_step(const OptTable& table,
               const void* data,
               std::uint32_t size,
               ArgAccessFn access,
               std::uint32_t& index,
               ParsedArg& out,
               const ParseOptions& options);

int parse_step_grouped(const OptTable& table,
                       const void* data,
                       std::uint32_t size,
                       ArgAccessFn access,
                       std::uint32_t& index,
                       ParsedArg& out,
                       std::string& group_buf,
                       const ParseOptions& options);

/// Yields ParsedArg views into the argv range; the range must outlive iteration.
class ParseIter {
public:
    using iterator_concept = std::input_iterator_tag;
    using value_type = std::expected<ParsedArg, ParseError>;
    using difference_type = std::ptrdiff_t;

    ParseIter() = default;

    ParseIter(const OptTable* table,
              const void* data,
              std::uint32_t size,
              ArgAccessFn access,
              ParseOptions options);

    const value_type& operator*() const {
        return current;
    }

    const value_type* operator->() const {
        return &current;
    }

    ParseIter& operator++() {
        advance();
        return *this;
    }

    ParseIter operator++(int) {
        ParseIter tmp = *this;
        advance();
        return tmp;
    }

    bool operator==(const ParseIter& other) const {
        return done && other.done;
    }

    bool operator!=(const ParseIter& other) const {
        return !(*this == other);
    }

private:
    void advance();

    const OptTable* table = nullptr;
    const void* data = nullptr;
    std::uint32_t count = 0;
    ArgAccessFn access = nullptr;
    std::uint32_t index = 0;
    ParseOptions options;
    bool done = true;
    value_type current;
    bool is_grouped = false;
    std::string group_buf;
    bool in_group = false;
    bool past_dash_dash = false;
};

/// Parse argv against the given option table. Returns a range of
/// expected<ParsedArg, ParseError>; the argv range must outlive iteration.
template <typename Range>
auto parse(const OptTable& table, Range& argv, ParseOptions options = {}) {
    using Elem = std::remove_cvref_t<decltype(argv[0])>;
    auto access = [](const void* d, std::uint32_t i) -> std::string_view {
        return static_cast<const Elem*>(d)[i];
    };
    return std::ranges::subrange(
        ParseIter(&table, argv.data(), static_cast<std::uint32_t>(argv.size()), access, options),
        ParseIter());
}

}  // namespace kota::option
