#pragma once

#include <cassert>
#include <expected>
#include <iterator>
#include <ranges>
#include <span>
#include <string>
#include <string_view>
#include <vector>

#include "option.h"
#include "kota/support/functional.h"

namespace kota::option {

/// Per-parse configuration: controls parsing behavior and option filtering.
/// Separate from OptTable so the same table can be parsed with different strategies.
struct ParseOptions {
    /// Support grouped short options, e.g. -abc represents -a -b -c.
    bool grouped_short_options = false;

    /// Whether "--" stops option parsing and treats all subsequent
    /// arguments as positional. E.g. `-- -a -b` gives two positional inputs.
    bool dash_dash_parsing = false;

    /// When dash_dash_parsing is on, pack everything after "--" into a single
    /// ParsedArg whose spelling is "--" and values contain the rest of argv.
    bool dash_dash_packing = false;

    /// Unknown options greedily consume subsequent values until a known
    /// option or "--" is encountered.
    bool greedy_unknown = false;

    /// Bitmask: only match options whose visibility intersects this value.
    std::uint32_t visibility = ~0U;

    /// If non-zero, only match options that carry at least one of these flags.
    std::uint32_t include_flags = 0;

    /// Exclude options that carry any of these flags.
    std::uint32_t exclude_flags = 0;

    bool excludes(const OptionRef& opt) const;
};

/// Immutable option definition table. Built once from a span of Option entries;
/// the constructor scans for input/unknown IDs, computes prefix data, and
/// determines the first searchable index. All fields are read-only after
/// construction.
struct OptTable {
    /// The option definitions this table was built from.
    std::span<const Option> option_infos;

    /// Union of all prefixes across all options, e.g. {"--", "-"}.
    std::vector<std::string_view> prefixes_union;

    /// Individual characters that appear in any prefix, e.g. {'-'}.
    std::vector<char> prefix_chars;

    /// ID of the Input sentinel option (0 if absent).
    std::uint32_t input_option_id = 0;

    /// ID of the Unknown sentinel option.
    std::uint32_t unknown_option_id = 0;

    /// Index of the first non-Input/Unknown/Group option in option_infos.
    std::uint32_t first_searchable_index = 0;

    /// Match option names case-insensitively.
    bool ignore_case = false;

    /// The option infos are sorted by name (e.g. generated by TableGen),
    /// so use binary search instead of linear scan.
    bool tablegen_mode = false;

    /// Search from index 0 instead of first_searchable_index, so that Input
    /// and Unknown entries also participate in the prefix/name scan.
    bool search_includes_input = false;

    OptTable(std::span<const Option> option_infos,
             bool ignore_case = false,
             std::vector<std::string_view> prefixes_union = {});

    std::optional<OptionRef> option(std::uint32_t opt_id) const;

    std::optional<OptionRef> find_option(std::string_view argument,
                                         std::uint32_t visibility = ~0U) const;

    /// Render a parsed argument back into argv fragments using the canonical
    /// option name (after alias resolution) and the option's render style.
    /// Invokes the callback once per rendered fragment.
    void render(const ParsedArg& arg, kota::function_ref<void(std::string_view)> cb) const;
};

/// Yields ParsedArg views into the argv range; the range must outlive iteration.
class ParseIter {
public:
    using iterator_concept = std::input_iterator_tag;
    using value_type = std::expected<ParsedArg, ParseError>;
    using difference_type = std::ptrdiff_t;

    ParseIter() = default;

    ParseIter(const OptTable* table, ArgsRef args, ParseOptions options);

    const value_type& operator*() const {
        return current;
    }

    const value_type* operator->() const {
        return &current;
    }

    ParseIter& operator++() {
        advance();
        return *this;
    }

    ParseIter operator++(int) {
        ParseIter tmp = *this;
        advance();
        return tmp;
    }

    bool operator==(const ParseIter& other) const {
        return done && other.done;
    }

    bool operator!=(const ParseIter& other) const {
        return !(*this == other);
    }

private:
    void advance();

    const OptTable* table = nullptr;
    ArgsRef args;
    std::uint32_t index = 0;
    ParseOptions options;
    bool done = true;
    value_type current;
    bool is_grouped = false;
    std::string group_buf;
    bool in_group = false;
    bool past_dash_dash = false;
};

inline auto parse(const OptTable& table, ArgsRef args, ParseOptions options = {}) {
    return std::ranges::subrange(ParseIter(&table, args, options), ParseIter());
}

template <typename Range>
auto parse(const OptTable& table, Range& argv, ParseOptions options = {}) {
    return parse(table, ArgsRef(argv), options);
}

}  // namespace kota::option
